routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@home')->name('home');
Route::get('/home', 'PagesController@home')->name('home');
Route::get('/search', 'PagesController@search')->name('search');
Route::post('/search', 'TicketController@search');
Route::group(['middleware' => 'auth'], function()
{
    Route::resource('tickets', 'TicketController');
});
Route::resource('tickets.comments', 'TicketCommentController');

Auth::routes();

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['comment'];

    public function ticket_id() {
        return $this->belongsTo('App\Ticket');
    }
}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'os', 'summary', 'status',
    ];

    public function user_id() {
        return $this->belongsTo('App\User');
    }

    public function ticket_comments()
    {
        return $this->hasMany('App\Comment');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user_tickets()
    {
        return $this->hasMany('App\Ticket');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function home()
    {
        return view('home');
    }

    public function search()
    {
        return view('search');
    }
}

app/Http/Controllers/TicketCommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ticket;
use App\Comment;
use App\User;
use App\Http\Requests\CommentFormRequest;

class TicketCommentController extends Controller
{
    public function index(Request $request, $ticket)
    {

        $comments = Comment::where('ticket_id', $ticket)->paginate(4);
        $currentTicket = Ticket::find($ticket);
        return view('comments.index', ['ticket' => $currentTicket, 'comments' => $comments])->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function create($ticket)
    {
        $currentTicket = Ticket::find($ticket);
        $comment = new Comment();
        return view('comments.create', ['ticket' => $currentTicket, 'comment' => $comment ]);
    }

    public function store(CommentFormRequest $request, $ticket)
    {
        $allRequest = $request->all();
        $currentTicket = Ticket::find($ticket);

        $comment = new Comment();
        $comment->comment = $allRequest['comment'];
        $comment->ticket_id = $currentTicket->id;
        $comment->save();

        $request->session()->put('ticket', $currentTicket);
        $request->session()->put('comment', $comment->comment);

        return redirect()->route('tickets.comments.create', ['ticket' => $ticket]) ->with('success','Comment added
        successfully');
    }

}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchFormRequest;
use App\Http\Requests\TicketFormRequest;
use Illuminate\Http\Request;
use App\Ticket;
use App\User;
use App\Comment;

class TicketController extends Controller
{
    public function create()
    {
        $ticket = new Ticket;
        return view('tickets.create', ['ticket' => $ticket ]);
    }

    public function index(Request $request)
    {
        $tickets = Ticket::with('ticket_comments')->orderBy('id', 'ASC')->paginate(4);
        return view('tickets.index',compact('tickets')) ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function show($id)
    {
        $ticket = Ticket::with('ticket_comments')->find($id);
        return view('tickets.show', ['ticket' => $ticket]);
    }




    public function edit($id)
    {
        $ticket= Ticket::find($id);
        return view('tickets.edit',compact('ticket'));
    }



    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'status' => 'required',
        ]);
        Ticket::find($id)->update($request->all());
        return redirect()->route('tickets.show', $id) ->with('success','Ticket status updated successfully');
    }

    public function destroy($id)
    {
        Ticket::find($id)->delete();
        return redirect()->route('tickets.index') ->with('success','Ticket deleted successfully');
    }

    public function store(TicketFormRequest $request)
    {
        $allRequest = $request->all();

        $ticket = new Ticket();
        $ticket->os = $allRequest['os'];
        $ticket->summary = $allRequest['summary'];
        $ticket->user_id = auth()->user()->id;
        $ticket->status = "Pending";
        $ticket->save();

        $comment = new Comment();
        $comment->comment = $allRequest['comment'];
        $comment->ticket_id = $ticket->id;
        $comment->save();

        $request->session()->put('ticket', $ticket);
        $request->session()->put('user', auth()->user()->name);

        return redirect()->route('tickets.show', $ticket->id) ->with('success','Ticket added
successfully');
    }

    public function search(SearchFormRequest $request)
    {
        $ticket_id = $request->only(['search']);
        $ticket = Ticket::find($ticket_id)->first();
        if($ticket==null)
        {
            return redirect()->route('search') ->withErrors(['Ticket not found!']);
        }
        else
        {
            return redirect()->route('tickets.show', $ticket->id) ->with('success', 'Ticket found!');
        }



    }
}

resources/views/comments/create.blade.php
@extends('layouts/default')

<main>
    @section('content')
        <div class="container m-5">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12 mt-5 text-center">
                    <div class="text-center">
                        <h2>Ticket {{$ticket->id}}</h2>
                    </div>
                </div>


                <div class="col-md-8 offset-md-2">
                    <!--Card-->
                    <div class="card hoverable">
                        <!--Card content-->
                        <div class="card-body">
                            <!--Title-->
                            <p class="card-text text-center">Operating System: </p>
                            <p class="card-block text-center">{{$ticket->os}}</p>
                            <hr>
                            <p class="card-text text-center">Issue summary: </p>
                            <p class="card-block text-center">{{$ticket->summary}}</p>
                            <hr>
                            <p class="card-text text-center">Comments:  </p>
                            @foreach($ticket->ticket_comments as $comment)
                                <p class="card-block text-center">{{$comment->comment}}</p><hr>
                            @endforeach

                            {!! Form::model($ticket, ['action' => 'TicketCommentController@store','route' => ['tickets.comments.store', $ticket->id]]) !!}
                            <div class="card-block text-center">
                                {!! Form::label('comment', 'New Comment') !!}
                                {!! Form::textarea('comment', null, array('placeholder' => 'Add New Comment','class' => 'form-control')) !!}
                            </div>
                            <div class="pull-right">
                                <button class="btn btn-success" type="submit">Add Comment</button>
                            </div>
                            <div class="pull-left">
                                <a class="btn btn-primary" href="{{route('tickets.comments.index', $ticket)}}">Back to Comments</a>
                            </div>

                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>
</main>

resources/views/comments/index.blade.php
@extends('layouts/default')

<main>
    @section('content')
        <div class="container m-5">
            <div class="row">
                <div class="col-md-12 mt-5 text-center">
                    <div class="pull-left">

                        <h2>All Comments for Ticket {{$comments->first()->ticket_id}}</h2>
                        <h4 class="pull-left">(Status: {{$ticket->status}})</h4>
                    </div>
                </div>
                    <table class="table table-bordered">
                        <tr>
                            <th>Number</th>
                            <th>Comment</th>
                        </tr>
                        @foreach ($comments as $comment)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $comment->comment}}</td>
                            </tr>
                        @endforeach
                    </table>
                <hr>

            </div>

            <div class="row">
                <div class="col-md-12 text-center">
                    <hr>
                    @if($ticket->status == 'Pending' | $ticket->status == 'In Progress')
                        <div class="pull-right">
                            <a class="btn btn-success align-content-center" href="comments/create">Add New Comment</a>
                        </div>
                        @else
                        <div class="pull-right">
                            <a class="btn btn-success disabled align-content-center" href="">Check Ticket Status</a>
                        </div>
                    @endif
                    <div class="pull-left">
                        <a class="btn btn-primary align-content-center" href="{{route('tickets.show', $comments->first()->ticket_id)}}">Back to Ticket {{$comments->first()->ticket_id}}</a>
                    </div>
                </div>
            </div>

            <div class="row">
                {!! $comments->links() !!}
            </div>

        </div>


</main>

resources/views/contact.blade.php
<section id="contact">
    <div class="col-md-8 offset-2">
        <ul class="list-unstyled">
            <li class="mb-4">
                <i class="fa fa-2x mb-3 fa-map-marker"></i>
                <p>Melbourne, VIC 3000, Australia</p>
            </li>

            <li class="mb-4"><i class="fa fa-2x mb-3 fa-phone"></i>
                <p>(03) 9925 2000</p>
            </li>

            <li class="mb-4"><i class="fa fa-2x mb-3 fa-envelope"></i>
                <p>RMIT University, GPO Box 2476, Melbourne VIC 3001 Australia</p>
            </li>
        </ul>

    </div>
</section>

resources/views/faq.blade.php
<section id="FAQ" class="text-center">
    <div class="container">
        <h3 class="flip"> How do I submit a support ticket? <b class="caret"></b></h3>
        <div class="panel">
            <p> 1. On the navigation menu, click "User Options", then "Create Ticket".</p>
            <p> 2. Input your details. </p>
            <p> 3. Click Submit Ticket. You should then be redirected to the Ticket Details page. </p>
            <br>
        </div>
        <h3 class="flip">How long does it usually take until my issue is resolved?<b class="caret"></b></h3>
        <div class="panel">
            <p> It depends on the problem. It can take from 1 day to 2 weeks. Tickets are typically resolved in a few
                days.</p>
        </div>
        <h3 class="flip">What if I resolved my issue and would like to cancel? <b class="caret"></b></h3>
        <div class="panel">
            <p> If you no longer need the support of IT Staff you can: </p>
            <p> 1. Search for your ticket under "User Options -> Search for ticket" </p>
            <p> 2. Input your ticket ID (You will have been notified of your ticket ID upon submission.</p>
            <p> 3. Add a comment to notify staff that problem is resolved and they will close your ticket.
                Alternatively, you can close your ticket yourself from this page. </p>
        </div>
    </div>
</section>

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">

<body>
    <header>
    @extends('master')
    @section('title', 'Home')
    @section('header')
    <!--Mask-->
    <div class="view hm-black-light">
        <div class="full-bg-img flex-center">
            <div class="container">
                <ul>
                    <li>
                        <h1 class="h1-responsive wow fadeInDown">ITS Ticketing System</h1>
                    </li>
                    <li>
                        <p class="wow fadeInDown" data-wow-delay="0.2s">Welcome to the ITS Ticket Submission system!
                            If you are experiencing difficulties with your IT system, please submit a ticket and the team will attempt to resolve your issue as soon as possible.</p>
                    </li>
                    @if (Auth::guest())
                        <li>
                            <a href="{{ route('login') }}" class="btn btn-primary btn-lg wow fadeInLeft" data-wow-delay="0.4s">Login</a>
                            <a href="{{ route('register') }}" class="btn btn-info btn-lg wow fadeInRight" data-wow-delay="0.4s">Register</a>
                        </li>
                    @else
                        <li>
                            <a href="{{ route('tickets.create') }}" class="btn btn-primary btn-lg wow fadeInUp" data-wow-delay="0.4s">Submit a Ticket</a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
    <!--/.Mask-->




    </header>
    @section('content')

    <main class="text-center">
        <div class="container">

            <h2 class="h2-responsive my-5">Frequently Asked Questions</h2>

            <!--Section: FAQ -->
            @include('faq')
            <h2 class="h2-responsive my-5">Contact us</h2>

            <!--Section: contact-->
            @include('contact')


        </div>
    </main>


</body>

</html>

resources/views/layouts/default.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>RMIT ITS Ticketing System</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{{asset('/css/mdb.min.css')}}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{{asset('/css/style.css')}}" rel="stylesheet">
</head>

<body>

<div id="app" class="p-5">

    @include('shared.navbar')
    @yield('content')
    @include('shared.footer')
</div>

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{{asset('js/jquery-3.1.1.min.js')}}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{{asset('js/popper.min.js')}}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{{asset('js/bootstrap.min.js')}}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{{asset('js/mdb.min.js')}}"></script>



<!--Animations initialisation-->
<script>
    new WOW().init();
</script>
</body>


</html>

resources/views/mask.blade.php
<html>
    <header>
        <!--Mask-->
        <div class="view hm-black-light">
            <div class="full-bg-img flex-center">
                <div class="container">
                    <ul>
                        <li>
                            <h1 class="h1-responsive wow fadeInDown">ITS Ticketing System</h1>
                        </li>
                        <li>
                            <p class="wow fadeInDown" data-wow-delay="0.2s">Welcome to the ITS Ticket Submission system!
                                If you are experiencing difficulties with your IT system, please submit a ticket and the team will attempt to resolve your issue as soon as possible.</p>
                        </li>
                        <li>
                            <a href="" class="btn btn-primary btn-lg wow fadeInLeft" data-wow-delay="0.4s">Submit a ticket</a>
                            <a href="" class="btn btn-default btn-lg wow fadeInRight" data-wow-delay="0.4s">Learn more</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--/.Mask-->
    </header>
</html>

resources/views/master.blade.php
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>RMIT ITS Ticketing System</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="../resources/assets/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="../resources/assets/css/mdb.min.css" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="../resources/assets/css/style.css" rel="stylesheet">
</head>

<body>

    @include('shared.navbar')
    @include('shared.footer')
    @yield('header')
    @yield('content')

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="../resources/assets/js/jquery-3.1.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="../resources/assets/js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="../resources/assets/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="../resources/assets/js/mdb.min.js"></script>


    <!--Animations initialisation-->
    <script>
        new WOW().init();
    </script>

    <!--Panel Slide Stuff -->
    <script>
        $(document).ready(function () {
            $(".flip").click(function () {
                $($(this).nextAll(".panel")[0]).slideToggle("slow");
            });
        });
    </script>
    <style type="text/css">
        .panel {
            padding: 40px;
            display: none;
        }

        h3 {
            padding-left: 20px;

        }
    </style>

</body>


</html>

resources/views/search.blade.php
@extends('layouts.default')
<main>
    @section('content')
        <div class="container m-5">
            <div class="row">
                <div class="col-md-12 mt-5 text-center">
                    <div class="text-center">
                        <h2>Search for a Ticket</h2>
                    </div>
                </div>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif


                <div class="col-md-8 offset-md-2 full-height">

                    {!! Form::open(['action' => 'TicketController@search']) !!}

                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" name="search" placeholder="Input Ticket ID...">
                        <span class="input-group-btn">
                    <button class="btn btn-default-sm primary-color" type="submit">
                    <i class="fa fa-search primary-color"></i>
                    </button>
                    </span>
                    </div>
                    {!! Form::close() !!}


                </div>
            </div>
        </div>
</main>

resources/views/shared/footer.blade.php
<html>
    <footer class="page-footer fixed-bottom black center-on-small-only">

        <!--links-->


        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2017 Copyright: <a href="edward.l.mumford@gmail.com"> Edward Mumford | WDA Assignment 1 | Uses Material Design for Bootstrap</a>

            </div>
        </div>
    </footer>
</html>

resources/views/shared/navbar.blade.php
<html>
    <nav class="navbar navbar-expand-lg navbar-dark black fixed-top mb-5">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('home')}}#FAQ">FAQ</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{route('home')}}#contact">Contact</a>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <!-- if user is a guest -->
                    @if (Auth::guest())
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">Register</a>
                        </li>
                        <!-- if user is logged in user -->
                    @else
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>
                                <a class="dropdown-item" href="{{route('tickets.create')}}">Create Ticket</a>
                                <a class="dropdown-item" href="{{route('search')}}">Search for Ticket</a>



                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
</html>

resources/views/tickets/card.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: heavenfall
 * Date: 18/8/17
 * Time: 2:11 PM
 */

resources/views/tickets/create.blade.php
@extends('layouts/default')
<main>
    @section('content')
    <div class="container m-5">
        <div class="row">
            <div class="col-md-12 mt-5 text-center">
                <div class="pull-left">
                    <h2>Add New Ticket</h2>
                </div>
            </div>
        </div>
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        {!! Form::model($ticket, ['action' => 'TicketController@store']) !!}

        <div class="row">
            <div class="col-md-12">
                <h4>Enter ticket details:</h4>
            </div>

            <div class="col-md-6 form-group">
                {!! Form::label('os', 'OS') !!}
                {!! Form::text('os', '', ['class' => 'form-control']) !!}
            </div>
            <div class="col-md-6 form-group">
                {!! Form::label('summary', 'Issue Summary') !!}
                {!! Form::text('summary', '', ['class' => 'form-control']) !!}
            </div>
            <div class="col-md-6 form-group">
                {!! Form::label('comment', 'Comment') !!}
                {!! Form::text('comment', '', ['class' => 'form-control']) !!}
            </div>

        </div>

        <button class="btn btn-success" type="submit">Submit Ticket</button>

        {!! Form::close() !!}
    </div>
</main>

resources/views/tickets/edit.blade.php
@extends('layouts/default')
<main>
    @section('content')
        <div class="container m-5">
            <div class="row">
                <div class="col-md-12 mt-5 text-center">
                    <div class="text-center">
                        <h2>Ticket {{$ticket->id}}</h2>
                    </div>
                </div>


                <div class="col-md-8 offset-md-2">
                    <!--Card-->
                    <div class="card hoverable">
                        <!--Card content-->
                        <div class="card-body">
                            <!--Title-->
                            <p class="card-text text-center">Operating System: </p>
                            <p class="card-block text-center">{{$ticket->os}}</p>
                            <hr>
                            <p class="card-text text-center">Issue summary: </p>
                            <p class="card-block text-center">{{$ticket->summary}}</p>
                            <hr>
                            <p class="card-text text-center">Comments:  </p>
                            @foreach($ticket->ticket_comments as $comment)
                                <p class="card-block text-center">{{$comment->comment}}</p><hr>
                            @endforeach
                            {!! Form::model($ticket, ['method' => 'PATCH','route' => ['tickets.update', $ticket->id]]) !!}
                            <p class="card-text text-center">Ticket Status: </p>
                            <div class="text-center">
                                {!! Form::select('status', array('Pending' => 'Pending', 'In Progress' => 'In Progress', 'Unresolved' => 'Unresolved', 'Resolved' => 'Resolved'), 'Pending'); !!}
                            </div>
                            <button type="submit" class="btn btn-success pull-right">Save Ticket</button>
                            <a class="btn btn-warning pull-left" href="{{route('tickets.index')}}">Cancel Edit</a>

                            {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>
        </div>
</main>

resources/views/tickets/show.blade.php
@extends('layouts/default')

<main>
    @section('content')
        <div class="container m-5">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12 mt-5 text-center">
                    <div class="text-center">
                        <h2>Ticket {{$ticket->id}}</h2>
                    </div>
                </div>


                    <div class="col-md-8 offset-md-2">
                        <!--Card-->
                        <div class="card hoverable">
                            <!--Card content-->
                            <div class="card-body">
                                <!--Title-->
                                <p class="card-text text-center">Operating System: </p>
                                <p class="card-block text-center">{{$ticket->os}}</p>
                                <hr>
                                <p class="card-text text-center">Issue summary: </p>
                                <p class="card-block text-center">{{$ticket->summary}}</p>
                                <hr>
                                <p class="card-text text-center">Comments:  </p>
                                @foreach($ticket->ticket_comments as $comment)
                                    <p class="card-block text-center">{{$comment->comment}}</p><hr>
                                @endforeach
                                <p class="card-text text-center">Status: </p>
                                <p class="card-block text-center">{{$ticket->status}}</p>
                                <hr>
                                <div class="text-center">
                                    <div class="d-inline">
                                        <a href="{{route('home')}}" class="btn btn-primary align-content-center" >Return to Home</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
            </div>
        </div>
</main>